// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7NreD3_cFkoYwJN-drF7yNovkADxmo0E',
    appId: '1:1029786050112:web:ef79f3cabc140c5d3a49a5',
    messagingSenderId: '1029786050112',
    projectId: 'flutter-vision-app',
    authDomain: 'flutter-vision-app.firebaseapp.com',
    databaseURL: 'https://flutter-vision-app.firebaseio.com',
    storageBucket: 'flutter-vision-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYjE-MOulVZfRmYg8Aet9kSLdf0pW6IWc',
    appId: '1:1029786050112:android:936690a2926c38583a49a5',
    messagingSenderId: '1029786050112',
    projectId: 'flutter-vision-app',
    databaseURL: 'https://flutter-vision-app.firebaseio.com',
    storageBucket: 'flutter-vision-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAntI9W5uH9tzozlCfoE_pDi433S1NPxeA',
    appId: '1:1029786050112:ios:ca8a7bf1e99bded63a49a5',
    messagingSenderId: '1029786050112',
    projectId: 'flutter-vision-app',
    databaseURL: 'https://flutter-vision-app.firebaseio.com',
    storageBucket: 'flutter-vision-app.appspot.com',
    iosClientId: '1029786050112-nlbsi5lk4ppljv9dqt6fvfkcge2tj97g.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterVision',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAntI9W5uH9tzozlCfoE_pDi433S1NPxeA',
    appId: '1:1029786050112:ios:ca8a7bf1e99bded63a49a5',
    messagingSenderId: '1029786050112',
    projectId: 'flutter-vision-app',
    databaseURL: 'https://flutter-vision-app.firebaseio.com',
    storageBucket: 'flutter-vision-app.appspot.com',
    iosClientId: '1029786050112-nlbsi5lk4ppljv9dqt6fvfkcge2tj97g.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterVision',
  );
}
